# Generated by Django 2.2.7 on 2019-11-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='receiver',
        ),
    ]
