# Generated by Django 2.2.7 on 2019-11-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20191120_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='comment_date',
            new_name='message_date',
        ),
    ]
