# Generated by Django 2.2.7 on 2019-11-21 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('message', '0008_auto_20191120_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Mesajlar'},
        ),
        migrations.CreateModel(
            name='MessageNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Mesaj')),
                ('message_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('has_parent', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciver_n', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_n', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-id'],
            },
        ),
    ]
