# Generated by Django 2.2.7 on 2019-11-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20191121_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagenew',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Mesajlar New'},
        ),
        migrations.RenameField(
            model_name='messagenew',
            old_name='has_parent',
            new_name='has_child',
        ),
    ]
