# Generated by Django 2.2.7 on 2019-11-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_messagenew_is_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
