# Generated by Django 2.2.7 on 2019-11-15 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=200, verbose_name='Haqqimda')),
                ('profile_photo', models.ImageField(blank=True, upload_to='', verbose_name='Profil shekili')),
                ('sex', models.CharField(blank=True, choices=[(None, 'Cinsiyyet'), ('male', 'Kisi'), ('female', 'Qadin')], max_length=6, verbose_name='Cinsiyyet')),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
