# Generated by Django 2.2.7 on 2019-11-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191115_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='member_since',
            field=models.DateField(auto_now_add=True),
        ),
    ]
