# Generated by Django 2.2.7 on 2019-11-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191115_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='member_since',
        ),
    ]
