# Generated by Django 2.2.7 on 2019-11-19 20:02

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userprofile_member_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default/default-profile.jpg', upload_to=user.models.upload_to, verbose_name='Profil shekili'),
        ),
    ]
