# Generated by Django 2.2.7 on 2019-11-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191120_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
