# Generated by Django 2.2.7 on 2019-11-19 22:19

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=20, verbose_name='Haqqimda'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default/default-profile.png', upload_to=user.models.upload_to, verbose_name='Profil shekili'),
        ),
    ]
