# Generated by Django 2.2.7 on 2019-11-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191120_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=200, verbose_name='Haqqimda'),
        ),
    ]
